name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: HawkN113
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Vienna
          
          # Common settings
          filename: github-metrics.svg
          
          # Programming languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, json, xml
          plugin_languages_details: percentage
          
          # Archive
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          
          # Articles
          plugin_posts: yes
          plugin_posts_source: external
          plugin_posts_limit: 5
          plugin_posts_user: external 
          plugin_posts_external: https://dev.to/feed/hawkn113, https://medium.com/feed/@nselyutin
