name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: HawkN113
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Vienna
          
          # Common settings
          filename: github-metrics.svg
          
          # Programming languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, json, xml
          plugin_languages_details: percentage

          # Achievements
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, deployer, member, maintainer, developer,
            scripter, packager, explorer
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
