name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          user: HawkN113
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Vienna
          
          # Programming languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, json, xml
          plugin_languages_details: percentage

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.posts.svg
          base: ""
          
          # Articles
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 4
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes
          
